### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by simonhammes** [mjakeman/extension-manager#667]
**Describe the bug**
The app does not start on Debian Testing when installed using apt.

```
libEGL warning: failed to get driver name for fd -1

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd -1


(extension-manager:19682): Gtk-WARNING **: 09:40:39.654: Unknown key gtk-modules in /home/simon/.config/gtk-4.0/settings.ini

(extension-manager:19682): GLib-GIO-ERROR **: 09:40:39.930: Settings schema 'com.mattjakeman.ExtensionManager' does not contain a key named 'width'
```

**System Information:**
 - Distro: Debian Testing
 - Extension Manager: 0.5.1-1
 - Package format: deb

**Additional context**
Workaround: The flatpak works.

**Comment by oscfdezdz** [comment]
> (extension-manager:19682): Gtk-WARNING **: 09:40:39.654: Unknown key gtk-modules in /home/simon/.config/gtk-4.0/settings.ini

Hi, could you check if you have the `gtk-modules` key in that file? If it is, comment it out and try starting it again.

**Comment by simonhammes** [comment]
> Hi, could you check if you have the `gtk-modules` key in that file? If it is, comment it out and try starting it again.

Hi, thanks for the reply. The file looks like this:

```ini
[Settings]
gtk-application-prefer-dark-theme=0
gtk-cursor-theme-name=breeze_cursors
gtk-cursor-theme-size=24
gtk-decoration-layout=icon:minimize,maximize,close
gtk-enable-animations=true
gtk-font-name=Noto Sans,  10
gtk-icon-theme-name=breeze
gtk-modules=colorreload-gtk-module
gtk-primary-button-warps-slider=false
gtk-xft-dpi=98304
```

I commented the `gtk-modules` line out. This caused the warning to disappear, but the _GLib-GIO-ERROR_ is still there. The application still crashes on startup.

**Comment by oscfdezdz** [comment]
Could you reinstall Extension Manager? That's the only thing I can think of right now, maybe the gschemas file has been updated or installed wrong.

About the libEGL warning, doesn't it happen with other GTK 4 applications?

**Comment by simonhammes** [comment]
> Could you reinstall Extension Manager? That's the only thing I can think of right now, maybe the gschemas file has been updated or installed wrong.

I've tried two things:
- `sudo apt install gnome-shell-extension-manager --reinstall`
- `sudo apt purge gnome-shell-extension-manager && sudo apt install gnome-shell-extension-manager`

Unfortunately the error persists :(

> About the libEGL warning, doesn't it happen with other GTK 4 applications?

Yeah, I tried `baobab` (46.0-1) and it causes the same libEGL warnings, so I guess they aren't the culprit.

**Comment by simonhammes** [comment]
I dug a little deeper and it seems like it broke with commit 911455667df6b3c054990307e3bcd3c9d8212327 (when checking out this repository), which seems to align with the error message.

The commit before that works :shrug: 

@oscfdezdz Nevertheless, thank you for your help!

**Comment by oscfdezdz** [comment]
I've done some research looking for the error and have come across other cases in GNOME core apps. It's usually an error when upgrading from an older version of the app. Recompiling the schemas should fix it:

`sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`

Although the command seems to affect all apps that use schemas so I recommend that you make a copy of the directory or schema file that is located in that path.

**Comment by simonhammes** [comment]
> Recompiling the schemas should fix it:
> 
> `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`

Thank you, but that did not fix the issue.

But I found out the root cause and managed to fix it:

> But this file does not exist 🤷

I was wrong, the file did not exist because I had removed the package earlier, before checking if the file exists :facepalm: 

I found out where it checks for `gschemas.compiled` files on startup using `strace -e trace=file -f extension-manager 2>&1 | grep schema`. This led me to `/usr/local/share/glib-2.0/schemas/gschemas.compiled`, where I had an older version of the file laying around (for whatever reason). After removing the XML file and the compiled binary file in this location, everything works :rocket:
